name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: ap:t-get update
        run: sudo apt-get update
  
      - name: build
        run: make

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: xv6.img
          path: xv6.img
  
  build-osx:
    runs-on: macos-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: brew upgrade
      run: brew upgrade

    - name: install make
      run: brew install make

    - name: install x86_64-elf-gcc
      run: brew install x86_64-elf-gcc

    - name: build
      run: make


