name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: apt-get update
        run: sudo apt-get update

      - name: build xv6.img
        run: make xv6.img
  
      - name: build fs.img
        run: make fs.img

      - name: gcc version
        run: gcc --version

      - name: show object files with sizes
        run: ls -la *.o

      - name: upload xv6.img
        uses: actions/upload-artifact@v4
        with:
          name: xv6.img-linux
          path: xv6.img
    
      - name: upload fs.img
        uses: actions/upload-artifact@v4
        with:
          name: fs.img-linux
          path: fs.img
  
      - name: upload kernel.sym
        uses: actions/upload-artifact@v4
        with:
          name: kernel.sym-linux
          path: kernel.sym

  build-osx:
    runs-on: macos-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: brew upgrade
      run: brew upgrade

    - name: install make
      run: brew install make

    - name: get binutils
      run: wget http://ftpmirror.gnu.org/binutils/binutils-2.21.1.tar.bz2

    - name: extract binutils
      run: bunzip2 binutils-2.21.1.tar.bz2

    - name: get gcc
      run: wget http://ftpmirror.gnu.org/gcc/gcc-4.5.1/gcc-core-4.5.1.tar.bz2

    - name: extract gcc
      run: bunzip2 gcc-core-4.5.1.tar.bz2

    - name: build xv6.img
      run: make xv6.img

    - name: build fs.img
      run: make fs.img

    - name: gcc version
      run: x86_64-elf-gcc --version

    - name: show object files with sizes
      run: ls -la *.o

    - name: upload xv6.img
      uses: actions/upload-artifact@v4
      with:
        name: xv6.img-osx
        path: xv6.img
  
    - name: upload fs.img
      uses: actions/upload-artifact@v4
      with:
        name: fs.img-osx
        path: fs.img

    - name: upload kernel.sym
      uses: actions/upload-artifact@v4
      with:
        name: kernel.sym-osx
        path: kernel.sym
